spring:
  datasource:
    url: jdbc:mysql://localhost:3306/love?serverTimezone=UTC&userUnicode=true&character=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
